### PR TITLE
Update to 1.29

### PR DESCRIPTION
**Pull request by trskop**
Hadn't tested it on MacOS. I'll update it if it breaks anything.

### CODE REVIEW

**Comment by justinwoo** [comment]
strange that this doesn't trigger a github actions run. maybe it's just busted

**Comment by justinwoo** [comment]
in the future if the nix installer works on osx again the workflow file can be edited to add osx

**Comment by justinwoo** [comment]
i.e. https://github.com/justinwoo/easy-dhall-nix/blob/1aa3b306e49cada554d8acfe3902e27527ecef98/.github/workflows/ci.yml#L10-L11

**Comment by justinwoo** [comment]
looks fine https://github.com/justinwoo/easy-dhall-nix/commit/1aa3b306e49cada554d8acfe3902e27527ecef98/checks?check_suite_id=400244433

**Comment by trskop** [comment]
Thanks @justinwoo for merging it so promptly.
Colleague noticed that MacOS was removed from the list. I'll try to get someone from Habito to test it on Mac.

**Pull request merged**
