### PR TITLE
Update to dhall 1.40.0

### PR DESCRIPTION
**Pull request by MasseR**
1.40.0 was released yesterday

### CODE REVIEW

**Comment by Profpatsch** [comment]
The macos releases are zip files now?

**Comment by MasseR** [comment]
Yeah, interesting. Since 1.40.0 the macos and windows packages are `tar.bz2.zip` files. I did a quick check on the dhall-haskell repository and didn't find anything obvious on this. I made an issue out of it: https://github.com/dhall-lang/dhall-haskell/issues/2295

**Comment by toastal** [comment]
This _needs_ to be 1.40.1 as 1.40.0 had critical bugs

**Comment by MasseR** [comment]
1.40.1 might not be enough, [there are still missing instances](https://github.com/dhall-lang/dhall-haskell/issues/2286), what do you think?

**Pull request closed without merging**
