### PR TITLE
[hack]: Fix macOS now that manpages are distributed with some tarballs

### LINKED ISSUE #39: Upstream macOS releases now contain more than `/bin`
It seems there's been a change in releases upstream, so that certain package tarballs (namely for `dhall` and `dhall-docs` on macOS, at least) contain more than just the `bin` directory. This causes `fetchzip` (after #28) to barf with

```
  trying https://github.com/dhall-lang/dhall-haskell/releases/download/1.36.0/dhall-1.36.0-x86_64-macos.tar.bz2
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100   657  100   657    0     0   8760      0 --:--:-- --:--:-- --:--:--  8878
  100 3077k  100 3077k    0     0  5241k      0 --:--:-- --:--:-- --:--:-- 5241k
  unpacking source archive /private/tmp/nix-build-source.drv-3/dhall-1.36.0-x86_64-macos.tar.bz2
  error: zip file must contain a single file or directory.
  hint: Pass stripRoot=false; to fetchzip to assume flat list of files.
```

I'm working on a PR to fix it, but I won't be mad if someone beats me to it.

### PR DESCRIPTION
**Pull request by jhenahan**
Fixes #39, though I'd be happier if there were a less hacky way to do this.

### CODE REVIEW

**Comment by Profpatsch** [comment]
https://github.com/justinwoo/easy-dhall-nix/pull/41 should fix the CI error.

**Comment by Profpatsch** [comment]
Hm, there should be a simpler way to tell fetchzip which directories are produced.

Also, are these only there on MacOS?

**Comment by Profpatsch** [comment]
I see some hashes for `release.json` changed, when I run `fetch.py` here, I don’t get the same updates. Did you update them manually? Or maybe are you running a different nix?

**Comment by jhenahan** [comment]
Oh, yeah, I updated those manually. The `stripRoot = false` made gave me a hash mismatch and I just dumped the result in to get it working.

And yes, it seems only the macOS releases bundle man pages, for whatever reason. The Travis config looks like it ought to happen for all releases, but the tarballs are just `bin` for the Linux releases.

**Comment by Profpatsch** [comment]
> I couldn't find a flag for `nix-prefetch-url --unpack` that'd get me the non-stripped root. I thought about using https://github.com/msteen/nix-prefetch with `fetchzip`, but it gave me a very ugly error about the `XDG_RUNTIME_DIR`.

Wait, so running `fetch.py` the next time would break this again? That won’t do I’m afraid :(

**Comment by Profpatsch** [comment]
> The main difference between fetchurl and fetchzip is in how they store the contents. fetchurl will store the unaltered contents of the URL within the Nix store. fetchzip on the other hand will decompress the archive for you, making files and directories directly accessible in the future. fetchzip can only be used with archives. Despite the name, fetchzip is not limited to .zip files and can also be used with any tarball. 

I guess that means we just switch to `fetchurl` instead (I haven’t used `fetchzip` before, so I never stumbled over this).

**Comment by jhenahan** [comment]
Yeah, I figured. :( I was trying to figure out a way to do it without just reverting #28, but the `fetch.py` issue is kind of a showstopper unless it can be made to work with `nix-prefetch fetchzip` or something.

**Comment by jhenahan** [comment]
Hmm, `fetchurl` actually isn't quite right, either. It fails with

```
bzip2: (stdin): trailing garbage after EOF ignored
unpacker produced multiple directories
```

I'll just use my hacky fork for the moment, but I'll try to come back to this this week. I expect I can just write an `unpackPhase` that does the right thing on Darwin rather than hacking the `installPhase`.

**Comment by Profpatsch** [comment]
I submitted an upstream issue, I think it would be better if we didn’t have to work around this: https://github.com/dhall-lang/dhall-haskell/issues/2104

**Comment by Profpatsch** [comment]
I spent some time and got a working more-or-less nice version: https://github.com/justinwoo/easy-dhall-nix/pull/43

**Pull request closed without merging**
