### PR TITLE
Add fetcher script and update to dhall 1.31.0

### PR DESCRIPTION
**Pull request by Profpatsch**
I was too lazy to bump manually, so I wrote a script.

### CODE REVIEW

**Comment by justinwoo** [comment]
looks like hell, approved

**Comment by Profpatsch** [comment]
I’m afraid I can’t merge though.

**Comment by justinwoo** [comment]
you can merge if you accept the collaborator invite

**Comment by trskop** [comment]
@Profpatsch, thanks for bumping the version.
Was thinking that nmattia/niv may be a way to handle the dependencies.

**Comment by Profpatsch** [comment]
> you can merge if you accept the collaborator invite

Ah cool, missed it in my mountain of notifications.

**Pull request merged**
